apiVersion: apps/v1
kind: Deployment
metadata:
  name: vinibeer
  labels:
    app: vinibeer
spec:
  replicas: 5
  template:
    metadata:
      name: vinibeer
      labels:
        app: vinibeer
    spec:
      nodeSelector:
        "kubernetes.azure.com/os-sku": Windows2022
      containers:
      - name: vinibeer
        image: viniaptmhq.azurecr.io/wincontainerintro:v2
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .5
            memory: 400M
        ports:
          - containerPort: 80
  selector:
    matchLabels:
      app: vinibeer
---
apiVersion: v1
kind: Service
metadata:
  name: vinibeer
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: vinibeer